### ISSUE TITLE
Simplify `bin's` naming in `Cargo.toml`

### ISSUE THREAD

**Issue by zie1ony** [odradev/odra#404]
Currently it is required to have such in `Cargo.toml`

```toml
[[bin]]
name = "my_project_build_contract"
path = "bin/build_contract.rs"
test = false

[[bin]]
name = "my_project_build_schema"
path = "bin/build_schema.rs"
test = false
```

It gets in the way when using workspace or even renaming the crate. The better way would be just name it `name = "build_contract"` and `name = "build_schema"`.
